field_config.type.*.third_party.google_vision:
  type: mapping
  label: 'Per-file type google_vision settings'
  mapping:
    google_vision:
      type: boolean
      label: 'Google vision'

google_vision.settings:
  type: config_object
  label: 'Google Vision settings'
  mapping:
    api_key:
      type: string
      label: 'Google Vision Api Key'
